-- ============================================================================
-- Migration: Add employee_daily_status table for pre-aggregated attendance
-- Purpose: Store computed daily status (P/A/HD/L/H/WO) for fast calendar queries
-- ============================================================================

-- Create the table
CREATE TABLE IF NOT EXISTS employee_daily_status (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID NOT NULL REFERENCES employees(id),
  date DATE NOT NULL,
  -- Computed status: P=Present, A=Absent, HD=Half-Day, L=Leave, H=Holiday, WO=WeekOff
  status VARCHAR(10) NOT NULL,
  -- If on leave, store the leave type code and ID
  leave_code VARCHAR(20),
  leave_type_id UUID,
  -- Attendance details (copied from raw attendance if present)
  check_in_time TIMESTAMP,
  check_out_time TIMESTAMP,
  work_minutes INT NOT NULL DEFAULT 0,
  is_late BOOLEAN NOT NULL DEFAULT FALSE,
  is_early_leave BOOLEAN NOT NULL DEFAULT FALSE,
  is_remote BOOLEAN NOT NULL DEFAULT FALSE,
  -- Metadata
  source_type VARCHAR(20) NOT NULL DEFAULT 'computed', -- computed, manual_override
  notes TEXT,
  computed_at TIMESTAMP NOT NULL DEFAULT now(),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  
  -- Unique constraint: one record per employee per day
  CONSTRAINT employee_daily_status_employee_date_key UNIQUE (employee_id, date)
);

-- Create indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_employee_daily_status_employee_date ON employee_daily_status(employee_id, date);
CREATE INDEX IF NOT EXISTS idx_employee_daily_status_date ON employee_daily_status(date);
CREATE INDEX IF NOT EXISTS idx_employee_daily_status_status ON employee_daily_status(status);

-- Add comment to table
COMMENT ON TABLE employee_daily_status IS 'Pre-aggregated daily attendance status for fast calendar rendering';
COMMENT ON COLUMN employee_daily_status.status IS 'P=Present, A=Absent, HD=Half-Day, L=Leave, H=Holiday, WO=WeekOff';
COMMENT ON COLUMN employee_daily_status.source_type IS 'computed=auto-generated by cron, manual_override=HR override';
